SEO-175665 - Angular doc changes
syncfusion-content/ej2-angular-docs pull request #297
Opened 2023-10-13 11:09 UTC by Sharly-Atieno

Hi @MallikaRK ,

Worked on page with redirect for Angular.

Regards,
Sharly A.

2023-10-13 11:10 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175665-Angular-chnages-](https://jenkins.syncfusion.com/job/Content/job/ej2-angular-docs/192/console)**

2023-10-13 11:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175665-Angular-chnages-](https://jenkins.syncfusion.com/job/Content/job/ej2-angular-docs/192/console)**

2023-10-13 11:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175665-Angular-chnages-](https://jenkins.syncfusion.com/job/Content/job/ej2-angular-docs/192/)<br/>**

2023-10-13 14:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175665-Angular-chnages-](https://jenkins.syncfusion.com/job/Content/job/ej2-angular-docs/193/console)**

2023-10-13 14:45 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175665-Angular-chnages-](https://jenkins.syncfusion.com/job/Content/job/ej2-angular-docs/193/)<br/>**

2023-10-17 06:50 UTC, Yvone-Atieno requested changes
Commented

2023-10-17 06:50 UTC, Yvone-Atieno commented on ej2-angular/toast/config.md
>  * [Customize the progress bar](./how-to/customize-progress-bar-theme-and-sizing/)
Check the above link

2023-10-17 06:54 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175665-Angular-chnages-](https://jenkins.syncfusion.com/job/Content/job/ej2-angular-docs/194/console)**

2023-10-17 06:54 UTC, Sharly-Atieno commented on ej2-angular/toast/config.md
>  * [Customize the progress bar](./how-to/customize-progress-bar-theme-and-sizing/)
Resolved

2023-10-17 06:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175665-Angular-chnages-](https://jenkins.syncfusion.com/job/Content/job/ej2-angular-docs/194/console)**

2023-10-17 07:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175665-Angular-chnages-](https://jenkins.syncfusion.com/job/Content/job/ej2-angular-docs/194/)<br/>**

2023-10-18 13:46 UTC, Yvone-Atieno approved these changes
Approved

2023-11-30 11:29 UTC, Aishwarya-Ganesan approved these changes
fine.

2023-12-07 14:52 UTC, merged